### ISSUE TITLE
Not sure how to start Webvirtcloud

### ISSUE THREAD

**Issue by ItsLeon15** [webvirtcloud/webvirtcloud#5]
So I tried following the setup instructions and all of the containers have started but I can't manage to get access to the panel? The response is "x.x.x.x sent an invalid response"? I've probably done something wrong and any help would be appreciated.

Is the ``custom.env`` supposed to stay the same or be changed to a custom domain?

**Comment by retspen** [comment]
Hello,

If you don't have your own domain and want to run locally you can use domain from example like in `custom.env`. Just add the next like to your `hosts` file:

```text
127.0.0.1       api.webvirt.local client.webvirt.local manage.webvirt.local assets.webvirt.local console.webvirt.local
```

**Comment by ItsLeon15** [comment]
Still not sure why this is happening, I've attached both the `/etc/hosts` file and the response from connecting to the site.
![image](https://github.com/webvirtcloud/webvirtcloud/assets/64979109/c96e23ed-1043-4bca-bb73-808858713373)
![image](https://github.com/webvirtcloud/webvirtcloud/assets/64979109/93bda1fa-dc0a-4980-9660-4911a6ea939d)

**Comment by cloudrack-ca** [comment]
I will state setting up from start to finish the whole aspect of webvirtcloud really is not making sense as ive stated prior your blog page brings us all to https://github.com/webvirtcloud/webvirtcloud#installation in order to install and setup but we still need to setup `compute` aspect no? this is another confusing aspect aswell but their should be an easier way to run everything and simply display ports out because utilizing virtcloud.local and so on and so forth for domains as i do own a domain cloudrack.ca i use it for coolify https://coolify.cloudrack.ca as well as a ip-cdn.cloudrack.ca does the same as slipp,io but with all said and done the ports are what needs to be called ive played around with this for about a week+ gave up more or less after 2-3 weeks its a very well thought out project as we can see documentation wise more or less and also by the code ive gotten everything running myself as well but cant get `compute` running theres no real

step 1 install req
step 2 install backend/frontend (what os as well as minimum specs as this is the main panel by the looks of it i.e heart and guts)
step 3 install backend (what os and preq)

more or less skim the code of
https://github.com/webvirtcloud/webvirtfrontend/tree/master/apps/web

this is the front-end on line `27` of file https://github.com/webvirtcloud/webvirtfrontend/blob/master/apps/web/package.json for local testing if not mistaken set 
`Line27`
```
    "dev": "vite",
```
to
```
    "dev": "vite --host",
```

**Comment by ItsLeon15** [comment]
So I can now get access to the admin section but where is the user section? Has this been made or is it still WIP?

**Comment by retspen** [comment]
Now we are working on VMs functionality, after that we will add users section

**Comment by ItsLeon15** [comment]
Ah okay, cool. This will be an amazing alternative to other paid VPS services. Good luck!
